### ADD PHOTO
POST https://dev.juliandworzycki.pl/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=ADD_PHOTO

--ADD_PHOTO
Content-Disposition: form-data; name="file"; filename="node.jpg"
Content-Type: image/jpeg

< ./node.jpg

--ADD_PHOTO
Content-Disposition: form-data; name="album"

album2
--ADD_PHOTO

### GET ALL PHOTOS
GET https://dev.juliandworzycki.pl/api/photos HTTP/1.1

### GET ONE PHOTO
GET https://dev.juliandworzycki.pl/api/photos/8 HTTP/1.1

### DELETE PHOTO
DELETE https://dev.juliandworzycki.pl/api/photos/8 HTTP/1.1