### GET ALL PHOTOS
GET https://dev.juliandworzycki.pl/api/photos HTTP/1.1
authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU

### GET PROFILE DATA
GET https://dev.juliandworzycki.pl/api/profile HTTP/1.1
authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU

### PATCH PROFILE DATA
PATCH https://dev.juliandworzycki.pl/api/profile HTTP/1.1
authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU

### SEND PROFILE IMAGE
POST https://dev.juliandworzycki.pl/api/profile HTTP/1.1
authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU
Content-Type: multipart/form-data; boundary=ADD_PROFILE_PHOTO

--ADD_PROFILE_PHOTO
Content-Disposition: form-data; name="file"; filename="node.jpg"
Content-Type: image/jpeg

< ./node.jpg

--ADD_PROFILE_PHOTO

### LOGOUT
GET https://dev.juliandworzycki.pl/api/profile/logout HTTP/1.1
authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU