### GET ALL USERS
GET https://dev.juliandworzycki.pl/api/user HTTP/1.1

### GET USER BY ID
GET https://dev.juliandworzycki.pl/api/user/1 HTTP/1.1

### GET USER ID BY EMAIL
GET https://dev.juliandworzycki.pl/api/user/email/a@a.a HTTP/1.1

### REGISTER USER
POST https://dev.juliandworzycki.pl/api/user/signup HTTP/1.1
content-type: application/json

{    
   "name": "a",
   "lastName": "a",
   "email":"a@a.aa",
   "password":"a",
   "nickName":"a"
}

### CONFIRM USER
GET https://dev.juliandworzycki.pl/api/user/confirm/1111 HTTP/1.1

### LOGIN USER
POST https://dev.juliandworzycki.pl/api/user/signin HTTP/1.1
content-type: application/json

{    
   "login":"a@a.a",
   "password":"a"
}

### UPDATE USER
PATCH https://dev.juliandworzycki.pl/api/user/update HTTP/1.1
content-type: application/json

{   
   "lastEmail":"a@a.aa",
   "newName": "a",
   "newLastName": "a",
   "newEmail":"a@a.a",
   "newNickName":"a"
}